version: '3.8'

services:
  backend:
    build: ./backend
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./backend:/usr/backend/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://prototype_dev:prototype_dev@db/prototype_dev
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=prototype_dev
      - POSTGRES_PASSWORD=prototype_dev
      - POSTGRES_DB=prototype_dev

volumes:
  postgres_data:
